### ISSUE TITLE
IDP credentials don't get cached unless ~/.bmx folder is manually created first

### ISSUE THREAD

**Issue by andrewalkema** [Brightspace/bmx#175]
### Description
Currently if you use bmx without creating the ~/.bmx folder it will prompt for IDP credentials on each call.  

### Tasks
* Modify the `SaveSessions` function in `saml/identityProviders/okta/file/oktaSession.go` to create the ~/.bmx directory before creating the sessions file.
* Create some tests to confirm savesessions will work whether or not this directory already exists

**Comment by cstavro** [comment]
Workaround for this right now would be to create a ~/.bmx folder so that the session file can be created.

**Comment by cfbao** [comment]
We're now treating this as a security feature, and BMX will tell users about this behaviour explicitly.

![image](https://github.com/Brightspace/bmx/assets/8552945/5bfdebae-aa58-419a-8c35-064e034403c2)
![image](https://github.com/Brightspace/bmx/assets/8552945/8944fbca-09ed-4885-826f-d1eb129b3fa5)
