### ISSUE TITLE
Investigate using Generic Host Builder for DI and config loading

### ISSUE THREAD

**Issue by boarnoah** [Brightspace/bmx#191]
.NET Core has generic [Host Builders](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostbuilder?view=dotnet-plat-ext-3.1) which adds support for config loading and DI in the same way as ASP.NET Core (i.e using ConfigureServices).

**Comment by cfbao** [comment]
I don't know how bmx is structured internally, but if it doesn't make sense to use a host, you can still use [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/), [Microsoft.Extensions.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/) and similar packages outside of hosts.

**Comment by boarnoah** [comment]
Attempting to use DI I realized I have written myself into a corner with the way I have BmxCore depends on other things (in this case CommandLine app) to have subscribe to events.

Requires refactoring.

**Comment by boarnoah** [comment]
Although System.CommandLine has support for use via Microsoft.Extensions.Hosting as far as I can tell it is in its infancy (many issues on github trackers related to design which makes me think how it works may change radically). 

Therefore decided to stick to only try using the other Extensions like Chenfeng suggested. 

Microsoft.Extensions.DependencyInjection:
Decided to opt for injecting dependencies manually at entrypoint, as far as I can tell this extension doesn't add support for auto injection of dependencies (the auto injection behavior seen within ASP.NET Core seems to be part of that project, and not this extension). 
Therefore it only really acts as a ServiceLocator, which as far as I can tell is considered something of an anti pattern. 

For these reasons it wasn't adding much value so I stuck to doing poormans/pure DI.

Microsoft.Extensions.Configuration:
Planning to make use of this to load the INI files used for config, will be a separate PR (since its a bit more involved with how it reads multiple config files).

**Comment by cfbao** [comment]
> Decided to opt for injecting dependencies manually at entrypoint, as far as I can tell this extension doesn't add support for auto injection of dependencies (the auto injection behavior seen within ASP.NET Core seems to be part of that project, and not this extension).
Therefore it only really acts as a ServiceLocator, which as far as I can tell is considered something of an anti pattern.

Microsoft.Extensions.DependencyInjection gives you constructor injection. It's similar to most other DI frameworks, and not meant to be used as a service locator.

You only have to call [`ServiceProvider.GetService`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider.getservice?view=dotnet-plat-ext-3.1) (or one of the [extension methods](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions?view=dotnet-plat-ext-3.1)) once (or a few times if you have nontrivial scopes or long running processes, unlikely for bmx though) at the root (i.e. `Main` in a console app). Every dependent services under the root can be auto injected via constructor arguments.

There are many blog posts on how to use it. Here's a [nice simple example](https://dev.to/ballcapz/adding-dependency-injection-to-net-core-console-applications-on-windows-3pm0).
Here's [a more involved example](https://github.com/Brightspace/deploymentqueue-serverless/blob/249ed2c529c43325580f9d216feadeb38036d7bf/src/DeploymentQueue.Discovery/Handler.cs#L24-L29) in an AWS Lambda handler with scopes.

**Comment by andrewalkema** [comment]
> > Decided to opt for injecting dependencies manually at entrypoint, as far as I can tell this extension doesn't add support for auto injection of dependencies (the auto injection behavior seen within ASP.NET Core seems to be part of that project, and not this extension).
> > Therefore it only really acts as a ServiceLocator, which as far as I can tell is considered something of an anti pattern.
> 
> Microsoft.Extensions.DependencyInjection gives you constructor injection. It's similar to most other DI frameworks, and not meant to be used as a service locator.
> 
> You only have to call [`ServiceProvider.GetService`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider.getservice?view=dotnet-plat-ext-3.1) (or one of the [extension methods](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions?view=dotnet-plat-ext-3.1)) once (or a few times if you have nontrivial scopes in a long running processes, unlikely for bmx though) at the root (i.e. `Main` in a console app). Every dependent services under the root can be auto injected via constructor arguments.
> 
> There are many blog posts on how to use it. Here's a [nice simple example](https://dev.to/ballcapz/adding-dependency-injection-to-net-core-console-applications-on-windows-3pm0).
> Here's [a more involved example](https://github.com/Brightspace/deploymentqueue-serverless/blob/249ed2c529c43325580f9d216feadeb38036d7bf/src/DeploymentQueue.Discovery/Handler.cs#L24-L29) in an AWS Lambda handler with scopes.

I'll add a ++ to Chenfeng's comment here.  

I agree Service Locator is an anti-pattern, but the reasons it's an anti-pattern are avoided by concentrating all the `ServiceProvider.GetService` stuff once at the root.  Every app needs an entry point, and ASP.NET Core is doing the same thing, just under the hood for you.  

Service Locator is bad because if I look at a class in our app, I should be able to tell what it depends on by what is injected into it's constructor, it should avoid magically spawning dependencies later on.  We don't have that problem by doing everything at the root one time.

I'm impressed you're this deep into the weeds and you're this new to dotnet.  Nice job, Adipa.

**Comment by boarnoah** [comment]
👍 thanks a lot for the feedback. Was helpful to know thoughts on DI stuff.

Moving config related work to #201
