### ISSUE TITLE
Rewrite Github actions to support .NET builds and tests and to create releases

### ISSUE THREAD

**Issue by boarnoah** [Brightspace/bmx#192]
.NET Core [supports](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) all the platforms we need to target.

For the non windows platforms it may be a good idea to publish as self contained (with the .NET Core runtime), since it might not be present. This increases the size of the release bundle a lot however.

Cosmetic:  Its possible to setup build configuration so that the hundreds of .DLLs in a self contained build are in a subfolder (https://stackoverflow.com/a/47867045/4433646). Worth attempting IMO.

**Comment by cfbao** [comment]
FYI, you can set `-p:PublishSingleFile=true` to publish to a single binary, and use `-p:PublishTrimmed=true` to reduce the size.
It's still quite large... (cost of not using Go)

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0
https://www.talkingdotnet.com/create-trimmed-self-contained-executable-in-net-core-3-0/
