### ISSUE TITLE
BMX has issues when running in Git Bash, MinGW

### ISSUE THREAD

**Issue by boarnoah** [Brightspace/bmx#215]
When running BMX in a shell like Git Bash, MinGW etc...  it is possible to get a bad response from Okta:
> Okta Password: [...] The handle is invalid

Unclear as to the root cause, but should ideally be fixed. Possibly with some better input sanitation prior to passing data to Okta's APIs

**Comment by Draculion** [comment]
Workaround is to use terminal or command prompt instead. (Not ideal, but can confirm that using Command Prompt instead of Git Bash allowed me to write a token)

**Comment by cfbao** [comment]
fixed in v3
