### ISSUE TITLE
write fails if .aws directory doesn't exist

### ISSUE THREAD

**Issue by amommersteeg-d2l** [Brightspace/bmx#376]
The following error is seen if the `.aws` directory doesn't exist. 
`2023/07/31 14:50:34 open C:\Users\{USERNAME}/.aws/credentials: The system cannot find the path specified.`

It would be nice if bmx just creates the directory for you.

**Comment by cfbao** [comment]
fixed by https://github.com/Brightspace/bmx/pull/373

**Comment by cfbao** [comment]
@amommersteeg-d2l the latest preview release contains this fix.
https://github.com/Brightspace/bmx/releases/tag/v3.0.0-preview-20230731

we will release v3 officially soon too.
